package com.sunil.imdbandroid.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunil.imdbandroid.db.model.IMBD;

import com.sunil.imdbandroid.db.model.IMBDDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iMBDDaoConfig;

    private final IMBDDao iMBDDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iMBDDaoConfig = daoConfigMap.get(IMBDDao.class).clone();
        iMBDDaoConfig.initIdentityScope(type);

        iMBDDao = new IMBDDao(iMBDDaoConfig, this);

        registerDao(IMBD.class, iMBDDao);
    }
    
    public void clear() {
        iMBDDaoConfig.clearIdentityScope();
    }

    public IMBDDao getIMBDDao() {
        return iMBDDao;
    }

}
