package com.sunil.imdbandroid.db.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "IMBD".
 */
@Entity
public class IMBD {

    @Id
    private Long id;
    private int movie_id;
    private String name;
    private Integer yearofrelease;
    private Double rating;
    private String imageurl;
    private String detailLink;

    @Generated(hash = 1906617484)
    public IMBD() {
    }

    public IMBD(Long id) {
        this.id = id;
    }

    @Generated(hash = 808979429)
    public IMBD(Long id, int movie_id, String name, Integer yearofrelease, Double rating, String imageurl, String detailLink) {
        this.id = id;
        this.movie_id = movie_id;
        this.name = name;
        this.yearofrelease = yearofrelease;
        this.rating = rating;
        this.imageurl = imageurl;
        this.detailLink = detailLink;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMovie_id() {
        return movie_id;
    }

    public void setMovie_id(int movie_id) {
        this.movie_id = movie_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getYearofrelease() {
        return yearofrelease;
    }

    public void setYearofrelease(Integer yearofrelease) {
        this.yearofrelease = yearofrelease;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getDetailLink() {
        return detailLink;
    }

    public void setDetailLink(String detailLink) {
        this.detailLink = detailLink;
    }

}
